### PR TITLE
Reintroduce "clocksTicked" parameter to fmi3CallbackIntermediateUpdate()

### PR DESCRIPTION
**Pull request by andreas-junghanns**

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
@MBlesken : is my re-intro change sufficient? It is surprisingly little I had to do, which makes me wonder, what I missed.
@t-sommer : On the C-code side: ok?
All: Torsten argues for better names in #1166 - this is the time to rename clocksTicked here as well, if we have a better suggestion.

**Comment by t-sommer** [comment]
Since there is no event iteration in SE,  I'd say `clocksTicked` is correct here.

**Comment by t-sommer** [comment]
I'm just wondering, why we have to signal clock ticks, but not events in the callback?

**Comment by andreas-junghanns** [comment]
> I'm just wondering, why we have to signal clock ticks, but not events in the callback?

In SE, all events are clocks.

**Comment by andreas-junghanns** [comment]
> 
> 
> > I'm just wondering, why we have to signal clock ticks, but not events in the callback?
> 
> In SE, all events are clocks.

@IZacharias , @MBlesken : please correct me if I am wrong...

**Review by IZacharias — APPROVED** [review]

**Review by MBlesken — APPROVED** [review]

**Pull request merged**
