### PR TITLE
Introduce f_disc to separate discrete state equations from f_event

### PR DESCRIPTION
**Pull request by rfranke**
This shall resolve issue #1450.
It enables the evaluation of output equations f_event independently
from state equations f_state with the fmi3Clock value fmi3ClockSubactive.
This is particularly needed for model exchange.

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
@rfranke : Please check my tiny change: I do not think that f_event should compute x_d - I removed x_d from the left-hand side of f_event to reflect this.
Reasoning: Your introduction of f_disc should give you complete control over computation of discrete states. If a getXXX triggers such a computation implicitly, this would not give you that desired control.

Another issue comes to mind: Some models might not be able to separate f_event and f_disc. Should we introduce a capability flag for the FMU `providesDiscreteStateControl`? If that is the case, we would have to explain that in the text as well.

**Review by andreas-junghanns — APPROVED** [review]
With my changes, I think this is ok - it makes the machinary more difficult to operate (one more function to support to split functionality of the update).
I am still wondering about the addition of a capability flag to indicate support of this feature, but this can be dealt with in a different PR.

**Comment by rfranke** [comment]
@andreas-junghanns your change looks good to me.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 
- Do we know of any tool that would not support the separation of the evalation  / update functions.
- Rüdiger: It might be tools that do not separate the previous.
- Claudio: Change "Activate output clocks and respective model partitions for the evaluation of discrete states in fdisc", as this seems not to be correct regarding the output clocks, I will change this
- Rüdiger: Change Activate clocks and respective model partitions in fevent
- Claudio: I wil change it.
- Masoud: I will check the case where the f_disc calculation is implicit.
- single out the question on the capability flag  (Christian)
- Mousoud: What is the use case for this features?
- Rüdiger: e.g. partial derivatives; in ME we need control over the evaluation of functions.

**Comment by clagms** [comment]
I've added a bit more, describing a bit more on the model partitions, and trying to summarize the semantics described in https://github.com/modelica/fmi-standard/issues/1450#issuecomment-866886765

@rfranke please have a look.

@andreas-junghanns  to make the PR more "complete", I think we still need to define the signature of the function `fmi3EvaluateDiscreteStates`. If this PR is to be merged without that, then we need to create an issue to not forget this.

**Review by andreas-junghanns — COMMENTED** [review]
@clagms : your latest changes are not acceptable: we have a section with mathematical description elements. We should not start just a few paragraphs below with a totally new section with new mathematical symbols that that never appear again.
Can you please use the definitions already layed out and if some semantic is missing, add it to what is alredy there in "2.1. Mathematical Definitions".

**Comment by clagms** [comment]
Understood @andreas-junghanns . However, right now I'm pretty flooded and I think only in 3-4 weeks will I find a bit of time to work on this. If you want to merge this PR without my additions, please revert and merge.

**Comment by andreas-junghanns** [comment]
@clagms and @rfranke : I changed your formulas to fit the math notation specified in "2.1 Mathematical Definitions" - please check that I did not mess up your intent.

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz : This was merged without your feedback - any second thoughts?

**Comment by chrbertsch** [comment]
@rfranke  Thanks for your work. The proposal seemed to be in a good state.
however there are no documented approved reviews. Have you coordinated with someone before merging this?
As the last changes were made by Andreas, I consider him to approve.
@clagms : could you please also comment, if every thing was fine for you?

**Comment by andreas-junghanns** [comment]
Sorry, @rfranke : Big Brothers are watching, not just you ;)

**Comment by t-sommer** [comment]
@rfranke, next time please rebase or squash (instead of merge) the PR, so we get a more streamlined `master` branch.

**Pull request merged**
