### PR TITLE
Move dependency information to model variables

### LINKED ISSUE #1114: Add dedicated causalities for clocks, continuous states, derivatives, and event indicators
We decided to list continuous time states, derivatives and event indicators as model variables in FMI 3 in order to simplify the description of dependencies. However these variables have a special meaning and API functions to access them. In order to properly describe the way these special variables can be accessed, I propose to introduce four additional causalities (as suggested by @friedrichatgc):

- clock
- continuousState (**edit**: redundant; can be inferred from `derivative` attribute)
- derivative (**edit**: redundant; can be inferred from `derivative` attribute)
- eventIndicator

Alternatively we could add new variable types (similar to `Clock`):

- ContinuousState
- Derivative
- EventIndicator

### PR DESCRIPTION
**Pull request by t-sommer**
fixes #1114 and #1115

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
This looks promising, to say the least. Let´s hope someone that is using dependencies will verify that your proposal does not miss any use case.

**Comment by masoud-najafi** [comment]
Currently the direct dependency of output-event(clock) wrt input-event (clocks) is not defined and is considered to be false by default. This may need to be updated and allow for some special cases a direct feed-through. I wonder if this change would allow adding output clock dependencies on input clocks (if decided)?

**Comment by andreas-junghanns** [comment]
> Currently the direct dependency of output-event(clock) wrt input-event (clocks) is not defined and is considered to be false by default. This may need to be updated and allow for some special cases a direct feed-through. I wonder if this change would allow adding output clock dependencies on input clocks (if decided)?

Why do you think such a outpu-input-clock dependency cannot be defined? Where is that excluded?

**Comment by masoud-najafi** [comment]
> 
> 
> > Currently the direct dependency of output-event(clock) wrt input-event (clocks) is not defined and is considered to be false by default. This may need to be updated and allow for some special cases a direct feed-through. I wonder if this change would allow adding output clock dependencies on input clocks (if decided)?
> 
> Why do you think such a outpu-input-clock dependency cannot be defined? Where is that excluded?
The input-clock and output clock variables should be treated in the same way as for regular input and output variables. I.e., the order of them may be respected in the XML (for display reasons). I did not found this in the text, may be I read it fast.
Unlike regular output variables, where dependencies on inputs and states are considered as TRUE, if "dependencies" attribute is not defined, for output clocks the default dependencies should be FALSE. 
In the next build, I will check if these can be done with recent changes in #1120

**Comment by t-sommer** [comment]
Wouldn't it be sufficient to simply add `dependencies=""` to the `<Clock .../>` element?

**Comment by t-sommer** [comment]
After discussing this PR with @KarlWernersson it turned out that the initial dependency information is only redundant for simple models and not allowing the re-ordering of states / derivatives and event indicators might be a burden for some tools (i.e. it's not redundant, as I previously thought). Also the continuous states cannot be derived from the `derivative` attribute, because these might point e.g. to inputs.

**Comment by TorstenBlochwitz** [comment]
@t-sommer, @KarlWernerssen: I don't understand the first point of your last comment. Why is not possible to add the dependency information directly to the variables?

I understand closing #1114: some variables can have more than one meaning at the same time (an input can be a derivative, an output can be a continuous state). For that reason neither the introduction of a new causality nor a new variable type works.

**Pull request closed without merging**
