### PR TITLE
Replace flags with vr sets for intermediate update setup

### PR DESCRIPTION
**Pull request by pmai**
This change reflects decisions at the FMI Design Meeting 2020-06-18 to
switch the all-on/all-off flags during instantiation to be variable
sets, thereby allowing for more precise control, as well as clearer
semantics during intermediateUpdate.

(partially addresses https://github.com/modelica/fmi-standard/issues/1068 )

### CODE REVIEW

**Comment by pmai** [comment]
> Looks very good.
> However, before merging this, we should first merge #1047 into master and into this PR (so perhaps the wording in 2_4 will have to change.)

I've looked at this, and there is only one small purely syntactic merge conflict in 2.4, which can easily be resolved on merging the PRs, so I don't think any pre-merging or order is imposed on the PRs (i.e. they can be merged in any order to master, with the conflict resolved on merging). I'll take care of this upon merging either one.

**Comment by pmai** [comment]
@t-sommer does this work for you? I don't really like the argument names all that much (CamelCase and n/N and very long), but that seemed to follow the pre-existing pattern...

**Comment by pmai** [comment]
Changed the function argument names to be slightly saner after short brainstorming with @t-sommer .

**Comment by pmai** [comment]
@chrbertsch I think this was not intended for the schema but for the function argument name to fmi3CallbackIntermediateUpdate, right? And was it decided to rename that to intermediateVariableSetRequired or intermediateVariableSetRequested? Both appear in the ticket write-up.

I can add the function argument renaming, though this does not really affect the API (function argument names are syntactically irrellevant), to this PR.

**Comment by chrbertsch** [comment]
> @chrbertsch I think this was not intended for the schema but for the function argument name to fmi3CallbackIntermediateUpdate, right? 

Yes, you are right. 

And was it decided to rename that to intermediateVariableSetRequired or intermediateVariableSetRequested? Both appear in the ticket write-up.

That confusion was un-intentionally, these names should mean the same. Personally I like intermediateVariableSetRequested better.

> I can add the function argument renaming, though this does not really affect the API (function argument names are syntactically irrellevant), to this PR.

OK, would be good.

**Pull request merged**
