### PR TITLE
Improve synchronous clocks example

### PR DESCRIPTION
**Pull request by clagms**
New iteration on the example motivating and explaining Synchronous Clocks.

### CODE REVIEW

**Review by andreas-junghanns — APPROVED** [review]

**Comment by andreas-junghanns** [comment]
@clagms : why is this still draft? Can we merge this?

**Comment by clagms** [comment]
Because I need to clarify some of the semantics in https://github.com/modelica/fmi-standard/issues/1199 
Our "mathematical" description is not correct as @klausschuch pointed out, and I was planning to fix that.
But if you want to merge this now, we can do that later. 
It would make sense that @klausschuch has another look at how I addressed his comments...

**Comment by andreas-junghanns** [comment]
> 
> 
> Because I need to clarify some of the semantics in #1199
> Our "mathematical" description is not correct as @klausschuch pointed out, and I was planning to fix that.
> But if you want to merge this now, we can do that later.
> It would make sense that @klausschuch has another look at how I addressed his comments...

Our current policy is to ask: is the standard better with after the merge?
If "yes", merge.
We need to move forward, we cannot wait until ALL related issues are fixed or we risk deadlocking all progress for fear of making incomplete improvements.

**Comment by andreas-junghanns** [comment]
Did you mark all open TODOs in the text or in tickets? If yes, either of us should merge. Now.

**Pull request merged**
