### PR TITLE
update overview table

### PR DESCRIPTION
**Pull request by chrbertsch**
The overview table is incorrect partially. 
The formatting of the "except ..." parts is not perfect, perhaps someone has a better idea.

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
I changed the table cells to be more explicit (I think).
Do you agree?

**Comment by chrbertsch** [comment]
> 
> 
> I changed the table cells to be more explicit (I think).
> Do you agree?
OK

**Comment by masoud-najafi** [comment]
Is "Direct Feedthrough" defined somewhere?

**Comment by andreas-junghanns** [comment]
> Is "Direct Feedthrough" defined somewhere?

I added this to the glossary with PR #941.

**Comment by clagms** [comment]
> Is "Direct Feedthrough" defined somewhere?

I think the "direct" qualifier in feedthrough is redundant. Feedthrough is feedthrough. There isn't any "indirect feedthrough".

**Comment by chrbertsch** [comment]
> I think the "direct" qualifier in feedthrough is redundant. Feedthrough is feedthrough. There isn't any "indirect feedthrough".

While in system theory one talks about the "feedthrough matrix", the behaviour when the feedthrough matrix is nonzero is also called "direct feedthrough", see e.g. https://en.wikipedia.org/wiki/State-space_representation
grafik

So I think, "direct feedthrough is the commonly used name, which we should used (and explain in the glossary)

(Perhaps this has been influenced by the usage of Mathworks, which in ML/SL talks about "nondirect feedthrough blocks" http://matrix.etseq.urv.es/manuals/matlab/toolbox/simulink/ug/how_si11.html like an integrator.) 

We should also link this to the useage of "dependencies" in the model structure, https://fmi-standard.org/docs/3.0-dev/#ModelStructure

**Comment by andreas-junghanns** [comment]
I added both terms (direct feedthrough and feedthrough with reference to the first) into the glossary in PR #941

**Comment by andreas-junghanns** [comment]
BTW: We should merge this PR - agreed?

**Pull request merged**
