### PR TITLE
Remove clocked variables from StepMode math

### PR DESCRIPTION
**Pull request by andreas-junghanns**

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
Added a sentene as per request.

**Review by masoud-najafi — APPROVED** [review]

**Comment by TorstenBlochwitz** [comment]
The changes look good to me. But when I read the document, I asked myself, if we clearly enough mention that clocked variable can be accessed only if one of its clocks ticks. We mention this only in one half sentence: 

The discrete-time variables xk and yk are called clocked variables. A clocked variable vk can acquire a new value and can be queried only when its Clock k is active, except during Initialization Mode.

Is this sufficient?

**Comment by TorstenBlochwitz** [comment]
We file a new ticket on that.

**Review by TorstenBlochwitz — APPROVED** [review]
OK. much better now.

**Pull request merged**
