### PR TITLE
Use the xref for fmi3SetInputDerivatives and fmi3GetOutputDerivatives

### PR DESCRIPTION
**Pull request by otronarp**

### CODE REVIEW

**Comment by chrbertsch** [comment]
@otronarp : we are currently working on #921 which will change these functions.

**Comment by chrbertsch** [comment]
(did not want to close it)

**Comment by otronarp** [comment]
@chrbertsch, but if you are changing their names I guess this should be closed?

**Comment by chrbertsch** [comment]
I have added the xrefs for the functions to #921

**Pull request closed without merging**
