### PR TITLE
Fix figure pseudocode algebraic loops

### PR DESCRIPTION
**Pull request by chrbertsch**
This PR addresses one point of #1015: it converts the graphics https://fmi-standard.org/docs/3.0-dev/images/ArtificialAlgebraicLoop.svg into a draw.io file and moves contained pseudocode to C-like code sections. 
(@t-sommer : should we should move these (later?) to reference-fmus/examples? Could you please help me with that?)

### CODE REVIEW

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
Have you made all vr_.* value references arrays with a single value on purpose?
One could make them atomic VRs and then write in the code:
fmi3SetFloat64(FMU2, &vr_FMU2_u1, 1, &s,        1);

This would be more C-like and maybe less confusing.
Let me know, if you want me to make this transformation.

**Review by t-sommer — CHANGES_REQUESTED** [review]
Please remove the obsolete SVG and changes to the Reference FMUs submodule.

**Comment by chrbertsch** [comment]
> Please remove the obsolete SVG and changes to the Reference FMUs submodule.

I removed the obsolete olf SVG image, but do not know how to revert the un-intentional changes to the Reference FMU submodule. @t-sommer  or someone else: could you help please? Thanks!

**Review by KarlWernersson — APPROVED** [review]

**Comment by andreas-junghanns** [comment]
I tried to improve the language and changed residue to residual because I think that is the proper math term.

**Review by andreas-junghanns — APPROVED** [review]

**Review by andreas-junghanns — APPROVED** [review]

**Review by t-sommer — APPROVED** [review]

**Comment by chrbertsch** [comment]
Hi Torsten,
Wie kann man denn meinen commmit zu dem Submodul Reference FMUs rückgängig machen?

Mit freundlichen Grüßen / Best regards

Christian Bertsch

Virtual Prototypes and Simulation (ME3) (CR/AEE3)
Robert Bosch GmbH | Postfach 10 60 50 | 70049 Stuttgart | GERMANY | www.bosch.com
Tel. +49 711 811-35799 | Mobile +49 152 53059884 | Fax +49 711 811-5195729 | Threema<threema://add/?id=RW37CBB6> / Threema Work<threemawork://add/?id=RW37CBB6>: RW37CBB6 | Christian.Bertsch@de.bosch.com<mailto:Christian.Bertsch@de.bosch.com>

Registered Office: Stuttgart, Registration Court: Amtsgericht Stuttgart, HRB 14000;
Chairman of the Supervisory Board: Franz Fehrenbach; Managing Directors: Dr. Volkmar Denner,
Prof. Dr. Stefan Asenkerschbaumer, Dr. Michael Bolle, Dr. Christian Fischer, Dr. Stefan Hartung,
Dr. Markus Heyn, Harald Kröger, Christoph Kübel, Rolf Najork, Uwe Raschke, Peter Tyroller
​

**Comment by t-sommer** [comment]
> Wie kann man denn meinen commmit zu dem Submodul Reference FMUs rückgängig machen?

It's resovled, see [files changed](https://github.com/modelica/fmi-standard/pull/1145/files).

**Pull request merged**
