### PR TITLE
Feature/hybrid co-simulation and intermediate variable access and scheduled execution simulation

### PR DESCRIPTION
**Pull request by APillekeit**
This version includes all changes discussed at the last FMI Design Meeting and the feedback from the pull requests:
* https://github.com/modelica/fmi-standard/pull/626
* https://github.com/modelica/fmi-standard/pull/627

Note: the following comments should be discussed at the next web meeting and are not related to the FCP:
https://github.com/modelica/fmi-standard/pull/626#issuecomment-541417410
https://github.com/modelica/fmi-standard/pull/626#issuecomment-541415665
https://github.com/modelica/fmi-standard/pull/626#issuecomment-541415609

### CODE REVIEW

**Comment by t-sommer** [comment]
> All png files or only png files newly introduced by the FCP07/10/15?

All new and changed PNGs, the rest as you see fit.

**Comment by t-sommer** [comment]
@APillekeit, you have not removed the PNGs themselves with fb5b35dcf68ac46623ff1b2434f1743d314296e6

**Comment by APillekeit** [comment]
> @APillekeit, you have not removed the PNGs themselves with fb5b35d

Don't mind to delete them all, but wouldn't it be good to keep them as a reference?
I suggest to discuss this in the webex.

**Comment by chrbertsch** [comment]
Regular Design Webmeeting: 

Following the discussion at the last design meeting in Lund, Andreas included the feedback.
Even though there was not so many technical reviews of this PR, we follow the decision from Lund to now merge and then continue improving on the Master.

Torsten will look in to the PNGs and then merge it, Andreas can support in case of questions.

**Comment by t-sommer** [comment]
Closing in favor of #662

**Pull request closed without merging**
