### PR TITLE
Fix ME feature entries

### PR DESCRIPTION
**Pull request by andreas-junghanns**
~~If this gets accepted, we need to fix the text to reflect that we allow Intermediate Update Mode also in ME.~~

### CODE REVIEW

**Review by chrbertsch — CHANGES_REQUESTED** [review]
I Propose to change from "check" to "--" and to add a legend what "check", "x", "-" mean

See https://github.com/modelica/fmi-standard/issues/1256#issuecomment-721237903

**Comment by andreas-junghanns** [comment]
> 
> 
> I Propose to change from "check" to "--" and to add a legend what "check", "x", "-" mean
> 
> See [#1256 (comment)](https://github.com/modelica/fmi-standard/issues/1256#issuecomment-721237903)

Why do we need 3 values?
I think the "--" values should be replace with "x" (meaning "No support", "no", "not included"...).
This would leave us with two, easily understood values and no legend is needed.

If you think we need three values, please describe here, what "--" means compared with "x" - and I will reintroduce the "--".

**Comment by andreas-junghanns** [comment]
Sorry: 8c7b580 commit message should read `Replace "--" with "icon:times[]"`

**Review by chrbertsch — CHANGES_REQUESTED** [review]
I do not like the "check" for "early return" and "intermediate update" for ME, as these terms are linked to a concrete realization and API calls for CS.

If we do not want to introduce  a "-" with legend entry "does not make sense for this FMU kind", we could just write "intrinsic ME feature"  or "not needed in ME" instead of the "check" in the cells.

**Review by KarlWernersson — CHANGES_REQUESTED** [review]
I agree with Christian,
The more i think of it the harder i think it is to make the table, what features should be mentionsed? we don't explain the features there so it could be hard to understand for someone just reading it without larger prior knowledge. And for someone with larger prior knowledge its not really necessary.

but at least a Not relevant tag (the way I interpretended the "-") is needed if we dont wat to change to much

**Comment by andreas-junghanns** [comment]
> 
> 
> I do not like the "check" for "early return" and "intermediate update" for ME, as these terms are linked to a concrete realization and API calls for CS.
> 
> If we do not want to introduce a "-" with legend entry "does not make sense for this FMU kind", we could just write "intrinsic ME feature" or "not needed in ME" instead of the "check" in the cells.

Agreed.
Why not have some brief text in the cells - we do that elsewhere in the table to make it more easily understandable?
I will work this into this PR as a proposal.

**Comment by andreas-junghanns** [comment]
> The more i think of it the harder i think it is to make the table, what features should be mentionsed? we don't explain the features there so it could be hard to understand for someone just reading it without larger prior knowledge. And for someone with larger prior knowledge its not really necessary.

Yes, this is a problem in all technical texts with significant depth.
The idea here is to introduce high-level concepts and in breadth-first fashion traverse the concept graph.
This can never be perfect, but we have to start somewhere to untangle the differences between the different FMI interface types.
We have to find a better way or leave this as the top-most traversal of the concepts, I think.

**Comment by andreas-junghanns** [comment]
I changed the cell entries to now "speak" a small number of words.
Maybe this is good enough?

**Review by chrbertsch — APPROVED** [review]

**Review by KarlWernersson — APPROVED** [review]

**Pull request merged**
