### PR TITLE
Regularize and expand Annotations

### PR DESCRIPTION
**Pull request by pmai**
This PR addresses the issues raised in #945 and #386. This mirrors mostly the SSP approach to annotations and regularizes differing versions in FMI (VendorAnnotations vs. Annotations).

Currently in draft form until all separate changesets have landed.

### CODE REVIEW

**Comment by chrbertsch** [comment]
Looks really good. 

@pmai : could you please also update and extend the standard text (2.2.7) possibly re-using part of the SSP description (2.1.1., 4.2 of https://ssp-standard.org/publications/SSP10/SystemStructureAndParameterization10.pdf)

**Comment by KarlWernersson** [comment]
Sorry, dinnt plan to change to ready for review, cant seem to find the undo button =(

**Comment by andreas-junghanns** [comment]
Poll during web design meeting:
Do you agree with the proposed direction of this PR (Adding Annotations at every element that is not a collection):
In Favour: Andreas, Pierre, Christian, Irina, Klaus, Otto, Torsten B
Against:
Abstain: Torsten S

@pmai : Please proceed with this PR.

**Comment by pmai** [comment]
This should now address all places where annotations might reasonably be used, and updates the documentation and images to match.

One might want to give the extension mechanisms like annotations and the extra directory a more central place in the outline, but I think this can be handled later on in the editing process if wanted.

So please review again, and comment where you think that I've now gone overboard with the places where annotations can be used...

**Comment by andreas-junghanns** [comment]
My understanding of XSD is patchy, my approval is based on naive pattern matching.

**Pull request merged**
