### PR TITLE
Move fmi3Instantiate*() functions to respective interface types

### LINKED ISSUE #1866: Clarify whether all constructor functions have to implemented
The FMI Spec states that 

> The FMU must implement all common API functions according to [Section 2.2](https://fmi-standard.org/docs/3.0/#general-mechanisms) and the functions for at least one of the interface types.

However the constructor functions (`fmi3Instantiate*()`) are all listed under "Common Functions" in [fmi3Functions.h](https://github.com/modelica/fmi-standard/blob/main/headers/fmi3Functions.h#L228)

```C
/***************************************************
Common Functions
****************************************************/

// ...

/* Creation and destruction of FMU instances */
FMI3_Export fmi3InstantiateModelExchangeTYPE         fmi3InstantiateModelExchange;
FMI3_Export fmi3InstantiateCoSimulationTYPE          fmi3InstantiateCoSimulation;
FMI3_Export fmi3InstantiateScheduledExecutionTYPE    fmi3InstantiateScheduledExecution;
```

even though they technically belong to the respective interface.

See also [#CATIA-Systems/FMPy/](https://github.com/CATIA-Systems/FMPy/issues/552).

### PR DESCRIPTION
**Pull request by t-sommer**
in header files

fixes #1866

### CODE REVIEW

**Comment by TorstenBlochwitz** [comment]
Hm, this pull request fine for me. However the specification text about which functions are mandatory should be improved. I will make a note in the tzicket.

**Review by TorstenBlochwitz — APPROVED** [review]

**Review by andreas-junghanns — APPROVED** [review]
maybe comments like "/* Destruction of FMU instances */" are superfluous - their names give away their purpose well enough, right?

**Comment by t-sommer** [comment]
I just tried to follow the conventions in the header file and it seems that all functions or groups of functions have some kind of leading comment.

**Review by chrbertsch — COMMENTED** [review]
The following functions are listed under "common functions", but are not present in all FMI kinds (not in SE)

- fmi3EnterEventMode
-  fmi3EvaluateDiscreteStates 
- fmi3EvaluateDiscreteStates (??,  Mentioned in 2.2.8 "Clocks, but 2.4.2. states
image
- fmi3UpdateDiscreteStates (??, mentioned in 2.2.8 "Clocks")

**Comment by chrbertsch** [comment]
Closed as it was decided to require all API functions

**Pull request closed without merging**
