### PR TITLE
Update link to Modelica Association CLA

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Comment by t-sommer** [comment]
What's the difference between v1.0 and v1.1.1?

**Comment by chrbertsch** [comment]
https://modelica.org/licenses/ModelicaAssociationCLA_1.1.1.html

**Comment by t-sommer** [comment]
That's v1.1 vs v1.1.1.

**Comment by beutlich** [comment]
> 
> 
> What's the difference between v1.0 and v1.1.1?

I am not aware of MA CLA v1.0 at all. Where did you see it?

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
https://svn.fmi-standard.org/fmi/branches/public/FMI_CCLA_v1.0_2016_06_21.pdf
is a broken link

**Comment by andreas-junghanns** [comment]
> 
> 
> > https://svn.fmi-standard.org/fmi/branches/public/FMI_CCLA_v1.0_2016_06_21.pdf no longer is available.
> 
> The document is availbale at https://github.com/modelica/fmi-design/blob/master/FMI_CCLA/FMI_CCLA_v1.0_2016_06_21.pdf
> 
> Shall we upload it to https://github.com/modelica/fmi-standard.org/tree/master/assets and link to there?

Should we link to a more general document, without version and date to have always the most recent file under this permanent link?

**Comment by t-sommer** [comment]
> > What's the difference between v1.0 and v1.1.1?
> 
> I am not aware of MA CLA v1.0 at all. Where did you see it?

Never mind. I was confused about the different CLA version numbers of FMI vs MA.

@chrbertsch, @andreas-junghanns, can you please approve, so we can fix the build?

**Review by chrbertsch — APPROVED** [review]

**Comment by t-sommer** [comment]
I've added an AsciiDoc version of the FMI CCLA, but we should give it a makeover before we merge it.

**Review by andreas-junghanns — APPROVED** [review]

**Pull request merged**
