### PR TITLE
Remove non-existent previous attribute documentation

### LINKED ISSUE #853: Please clarify the name of the attribute "previous" in Discrete time state
This issue comes as a result of a discussion on the solution to #738 .
The name "previous" conveys little meaning as to what this attribute should contain.

In the standard, it says: "Discrete-time states are listed in the ModelStructure and have the variable xml-attribute previous referring to the variable holding the previous value of the state."
I guess that "previous value" means the value of the discrete time state at the previous tick (in the same sense that $x_{j-1}$ refers to the previous value of $x_j$).
Is that correct? 

Or does "previous" mean the value at the previous super dense time instant?

### PR DESCRIPTION
**Pull request by pmai**
Same as future perfect it was found not to be...
Fixes #853 and #738

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
I found a few more dead xrefs and removed those.

**Comment by chrbertsch** [comment]
Regular Design Meeting:

Markus: I will review it. 

Klaus: there was a discussion in the hybrid CS group, do we remember it?

Andreas: The text does not explain it.  If someone needs it, it could be re-added.

Klaus: there were three interpretations

Markus: none of it really makes sense

Pierre: it is not in the Model Description. We should remove it now, but ask @KarlWernersson .

**Comment by andreas-junghanns** [comment]
I sent an email to Karl, but got no response. I take this as a "don´t care" or "don´t care now". Merging now.

**Comment by KarlWernersson** [comment]
Had to take care of sick daughter yesterday. So i was not available.
Please let me know, why was previuous droped?
Im still trying to catch up on what has happend while I was away

**Comment by andreas-junghanns** [comment]
@KarlWernersson: The way the previous attribute was (not) described let us to believe that this was a leftover from an intermediate stage of the hybrid Co-Sim group. If you want to reintroduce it, please create a PR with explanations and all such that we know the semantics, XSD changes, use cases etc.

**Comment by andreas-junghanns** [comment]
Here are a few questions that need to be answered:
“previous state” needs better definition:
 - previous doStep time?
 - Left-side value at events?
 - event iteration last super-dense time step?
Use case:
 - Why would the solver need to know the previous state from the model?
 - The solver knows whatever it needs from previous by memorizing itself, not so?

**Pull request merged**
