### PR TITLE
Fix math sm inconsistency 1158

### PR DESCRIPTION
**Pull request by clagms**
Fixes https://github.com/modelica/fmi-standard/issues/1158

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz : Can you please check - this is beyond me...

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz : can you please check and approve this PR?

**Comment by KarlWernersson** [comment]
Great fixes leftover garbage from #704 #394 #405

**Comment by andreas-junghanns** [comment]
> 
> 
> Great fixes leftover garbage from #704 #394 #405

I take this as approval. I will merge now.

**Pull request merged**
