### PR TITLE
Fixes to 3.2 (ME API)

### LINKED ISSUE #1016: Review of 3.2 (ME API)
https://fmi-standard.org/docs/3.0-dev/#_application_programming_interface: 
If the super-dense time before a call to
-  [x] explain argument `x`; describe or reference internal order of the argument x of `fmi3SetContinuousStatesTYPE`, also referring to array serialization
grafik

- [x] In explanation of `fmi3NewDiscreteStatesTYPE`: Correct sentence " fmi3NewDiscreteStates was (tR,tI), then the time instant after the call is (tR,tI)." to "... after the call is (tR,tI**+1**)."

- [x] I do not understand the non-normative text below the definition of `fmi3EnterContinuousTimeModeTYPE`: 

> [This function might be used for the following purposes:
>     If the FMU stores results internally on file, then the results after the initialization and/or the event has been processed can be stored.
>     If the FMU contains dynamically changing states, then a new state selection might be performed with this function.]

- [x] Describe the order of the the continues states returned from 
`typedef fmi3Status fmi3GetContinuousStatesTYPE` ...

- ~~in the text a function `fmi3EnterContinuousTimeModeTYPE(fmi3Instance instance);` is defined, but in the state machine for ME, the function  `fmi3EnterStepMode `is displayed (which belongs to CS, right?):
grafik~~

- [x]  Text below ME State machine: 

>  For example, the state chart indicates that when an FMU for Model Exchange is in state Continuous-Time Mode, a call to fmi3Set{VariableType} for a discrete input is not supported.

This was true for FMI2.0, but in FMI 3.0 this cannot be seen from the state machine. Replace this text with  a new one telling that the State machine displayes allowed transitions (and call of transition functions), but the allowed calls to functions in each state are defined in the text below.

- [x] Generally missing in 3.2.3.x: Detailed list of allowed and forbidden function calls. -> singled out as #1151 

~~- 3.2.3.6: missing point at the end.~~

- [x] 3.2.5. Clocks API:  "For a outputClock, the environment" --> "For an ..."

### PR DESCRIPTION
**Pull request by chrbertsch**
Resolves #1016 

except for #1151 

Strangely, in https://github.com/modelica/fmi-standard/commit/5e2b4f47a9ebabd4499962df5535a9f524489829 I had to introduce a dummy Todo line to get correct formatting. Could someone familier with adoc please check?

### CODE REVIEW

**Review by andreas-junghanns — APPROVED** [review]
I fixed your formatting TODO - if you agree, please merge or let me know and I will merge this.

**Comment by chrbertsch** [comment]
@andreas-junghanns : 

So you had to remove the comment line 
_[If the <<independent>> variable is `time`, `stopTime` is the stop time of the simulation.]_
to get awas with the ToDo problem.

Do we no longer want this comment? What was the reason for the problem.

Could you please merge, if the rest is fine for you? Thanks!

**Comment by andreas-junghanns** [comment]
I thought this was the line you wanted removed...
Your comment said "this" line - so I had to pick.
Removing the line below made less sense.
And the comment I removed adds no information, right?

I am available on the on the phone, we can discuss this quickly to resolve this.

The issue you had was that anchors have restrictions on where to place them. I looked at other anchor placements and this one seemed to have worked ok.

**Comment by chrbertsch** [comment]
@andreas-junghanns : the comment can be removed indeed. I also fixed the formatting by moving the anchor above. This PR can b merged from my side now.

**Pull request merged**
