### PR TITLE
V2.0.3release

### PR DESCRIPTION
**Pull request by chrbertsch**
add changelog and update documents with correct date

### CODE REVIEW

**Comment by chrbertsch** [comment]
@t-sommer : what else has to be done for the release after merging of this PR?

- tagging 
- create draft release note (based on changelog
- creation of zip file and .tar.gz file (or does this get created automatically?
- release

**Review by andreas-junghanns — APPROVED** [review]
There is a minor issue: a space missing in the addition to 2.3 after a dot '.' at the end of a sentence and the 'The' of the next.
I approve here because this is minor.

**Comment by t-sommer** [comment]
> @t-sommer : what else has to be done for the release after merging of this PR?
> 
> * tagging
> * create draft release note (based on changelog
> * creation of zip file and .tar.gz file (or does this get created automatically?

No.

> * release

If you can send me the PDFs and prepare the release notes, I can take care of the rest.

**Comment by chrbertsch** [comment]
> There is a minor issue: a space missing in the addition to 2.3 after a dot '.' at the end of a sentence and the 'The' of the next.
I approve here because this is minor.
Fixed

**Pull request merged**
