### PR TITLE
Remove buildConfiguration from modeldescrpition.xml 

### PR DESCRIPTION
**Pull request by chrbertsch**
as this information is now contained in builddescription.xml.

The generated graphics 
grafik
still contains the BuildConfiguration.

Could someone familiar with the machinary of creating the graphics from the xsd-s please re-generate the graphic?

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
@clagms : can you please look at rebuilding the image @chrbertsch found to be old?

**Comment by andreas-junghanns** [comment]
This is still a draft until we have fixed the image. I think.

**Comment by clagms** [comment]
@chrbertsch could you make this PR editable? I cannot push changes to it. Thank you!

**Comment by clagms** [comment]
> @chrbertsch could you make this PR editable? I cannot push changes to it. Thank you!

Nevermind @chrbertsch ... My git client was silly :)

**Comment by clagms** [comment]
@chrbertsch @andreas-junghanns , I think that the image has been re-generated from some other commit.
After pulling the latest changes from the master and merging them into this PR, I re-generated the images and there were no new changes.
After rebuilding the doc, and going to the picture that @chrbertsch referred to, I saw that there was no build configuration there as well.

@chrbertsch , in the future, to regenerate the images all you have to do is open powershell on the repository, and run (this is documented in Contributing.adoc):
```
.\.circleci\generate_figures.ps1
```

**Pull request merged**
