### PR TITLE
Include text from headers in source listings

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Comment by pmai** [comment]
Looks good on first look, however there seems some jumbled comments in the fmi3TypesPlatform.h and I'd switch back to C90-style comments for the headers, since nothing in there needs C99 for now (might change if we switch to use C99 types in the future, but I'd do this changeover later, if needed).

Will commit fixes in the next couple of minutes...

**Comment by andreas-junghanns** [comment]
end tag is missing for // tag::VariableTypes[]

**Comment by andreas-junghanns** [comment]
// tag::Component[]
copy-paste errors - used also where they should be renamed

**Comment by andreas-junghanns** [comment]
The fmi3Binary argument in fmi3SetBinaryTYPE still does not have a name. Did we not commit that fix?

**Comment by andreas-junghanns** [comment]
fmi3CompletedIntegratorStepTYPE argument list needs a line break

**Comment by pmai** [comment]
I'm in the process of fixing those, commit landing any minute now...

**Comment by andreas-junghanns** [comment]
just making sure you know those I also found...

**Comment by pmai** [comment]
This should hopefully address all missing instances, and switch the headers to back to C90 compatibility for now.

**Comment by andreas-junghanns** [comment]
No, I noted all the odd things I saw.

**Pull request merged**
