### PR TITLE
Make input initial=exact

### PR DESCRIPTION
**Pull request by andreas-junghanns**

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
This is an alternative solution to #1244 - as @t-sommer suggested.

**Review by t-sommer — APPROVED** [review]

**Comment by chrbertsch** [comment]
Setting initial=exact makes the start value for inputs mandatory. Is this intended and was this also the case before?

**Comment by andreas-junghanns** [comment]
> Setting initial=exact makes the start value for inputs mandatory. Is this intended and was this also the case before?

Yes, in FMI 2.0 input variables had to provide start values.
This re-definition (requiring inputs to have "initial = exact") makes the text in many ways simpler, because the "causality = input" case is not special anymore, but subsumed under the "initial = exact".

**Comment by andreas-junghanns** [comment]
@KarlWernersson & @chrbertsch : Can you look at this and approve, please?
If you do, I would close PR #1244.

I want these PRs accepted or rejected because we will go into a WriteFest tomorrow - your feedback today would be good - thanks!

**Review by chrbertsch — APPROVED** [review]

**Review by KarlWernersson — APPROVED** [review]
I like it.

The problem originate in this fix
https://github.com/modelica/fmi-standard/issues/271

**Comment by jph-tavella** [comment]
This applies to FMI 3.0, though, so I'm not sure how should we consider it for 2.0.1?

**Pull request merged**
