### PR TITLE
add dependencies on tunable parameters

### PR DESCRIPTION
**Pull request by chrbertsch**
fixing #424

### CODE REVIEW

**Comment by friedrichatgc** [comment]
I'm not sure if tunable parameters should be added here:
Why adding tunable parameters but not (normal) parameters?
The dependencies are used to get (directional) derivatives of the unknowns wrt the knows. For FMI 3.0 it was decided that (as for FMI 2.0) this does NOT include derivatives wrt parameters.
The topic of having derivatives wrt parameters was added to the DAE working group which will not go into 3.0.
So I think issue #424 should be moved to > FMI 3.0.

**Comment by chrbertsch** [comment]
> Why adding tunable parameters but not (normal) parameters?

This could be discussed. 

> The dependencies are used to get (directional) derivatives of the unknowns wrt the knows. For FMI 3.0 it was decided that (as for FMI 2.0) this does NOT include derivatives wrt parameters.

Ah, I was not aware of this. What have been the reasons? When was this discussed and to we have notes on that discussion?

> The topic of having derivatives wrt parameters was added to the DAE working group which will not go into 3.0.

What is the Link of this topic to DAEs?

**Comment by friedrichatgc** [comment]
The only reason for adding tunable parameters but not "normal" parameters I see is that for tunable parameters derivatives may be "emulated" by the environment using finite differences. For "normal" parameters this is not possible. But why requiring a parameter to be tunable to get (analytical) derivatives wrt the parameter. Hence, I propose to add all parameters.

> When was this discussed and to we have notes on that discussion?

See https://github.com/modelica/fmi-design/blob/master/WorkingGroups/02_DAE_PartialDerivatives/Meetings/2016-06-28-FMI-Meeting-Renningen/DerWrtPar.pdf for a proposal. This proposal basically states that adding parameters to the list of knowns is enought (as done with this PR). But some concerns regarding models with a very large number of parameters are given in the last slides. (but I don't remember details)

> What is the Link of this topic to DAEs?

None, I was also surprised about the decision to move this to the DAE working group.

In general I think we may need a capability flag whether the FMU can calculate derivatives wrt parameters or not since many tools can provide derivatives wrt inputs/states but not wrt parameters as needed for the more special case of optimization.
Moreover some text is needed for the use case of derivatives wrt parameters.

**Comment by andreas-junghanns** [comment]
I am unconvinced. What is the use case for derivatives on parameters?
In ECUs, parameters are flashed. One change.
Tuning is a manual process, sometimes semi-automatic.
What restrictions do you want to model with derivatives?

**Comment by chrbertsch** [comment]
> What is the use case for derivatives on parameters?

see slide 4 of https://github.com/modelica/fmi-design/blob/master/WorkingGroups/02_DAE_PartialDerivatives/Meetings/2016-06-28-FMI-Meeting-Renningen/DerWrtPar.pdf

**Comment by andreas-junghanns** [comment]
> 
> 
> > What is the use case for derivatives on parameters?
> 
> see slide 4 of https://github.com/modelica/fmi-design/blob/master/WorkingGroups/02_DAE_PartialDerivatives/Meetings/2016-06-28-FMI-Meeting-Renningen/DerWrtPar.pdf

Ok, makes sense - this is quite useful to have.

**Comment by chrbertsch** [comment]
Regular Design meeting: 

Markus: this introduces a large change, one has to check a lot of text
Claudio: One has to clearly defined what the derivatives w.r.t parameters mean
Markus: instant sensitivitiy in the sense of a Jacobian
Claudio: do tunable parameters change the outputs instantaneously?
Klaus: in ME they can have an imediate effect, in CS not
Markus: in CS you cannot emulate the partial derivatives numerically with deltas
Klaus: Do we not have dependencies on parameters in initial unknowns?
Markus: at most places talking about partial derivatives, we implicitely mean states and inputs. this is also how tools use it.
Is it allowed to get the partial derivatives in initialization mode?
Klaus: We might have a problem also for initial unknowns.
Markus: this is a smaller problem
Andreas:  Can we move this topic in 3.1?
Markus: I think we can, see slides of DAE proposal

Klaus: in 2.0 it is allowed to list parameters in initial unknowns. At least in ME one can call partial derivatives. 
Claudio: it is not easy to allow partial derivatives in step mode.
Claudio: in FMI 3.0, variables that can be changed in initial model, can be listed.

Decision: This is a too large change for FMI 3.0.

**Pull request closed without merging**
