### PR TITLE
Update type names in documentation, schema and examples (#669)

### PR DESCRIPTION
**Pull request by andreas-junghanns**

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
I tried to remove Real wherever needed (will send Integer PR right after).

Missing also fixes in the function-call tables.

**Comment by chrbertsch** [comment]
there is several times the occurance of "A vector of real  ..." in 3.1.1 (line 166ff. )  and 4.1.1.
Shall this be changes also? To "float"

3.1.2 This mode is used to compute the values of all (real) continuous-time variables 

Tables in 3.2.3  and 4.2.1
grafik
grafik

Code Example in 3.2.4
grafik

4.1.1
Step Mode
This mode is used to compute the values of all (real) continuous-time and discrete-time variables at communication points by 

Code Example for fmi3CoSimulation in 4.2.1
grafik

Same for 4.2.4

And pseudocode for SES; several times, e.g.: 
grafik

**Comment by andreas-junghanns** [comment]
I fixed most of Christian´s suggestions. Missing:
 - table entries: there is a lot more that needs fixing in the tables and it is not enough to set {VariableType} here as entries are different for floating point and integer types and is outside the scope of this PR
 - pseudo code in SES: This is for AndreasP to fix and should not go into this PR

**Comment by andreas-junghanns** [comment]
This is a big change set - can the reviewer please check this soon to avoid merge conflicts, please?

**Comment by chrbertsch** [comment]
Do we have to define the newly introduced term "numeric type"?

**Comment by andreas-junghanns** [comment]
> Do we have to define the newly introduced term "numeric type"?

Why define "numeric type"? Any type with a number is numeric. Standard comp sci.

**Comment by chrbertsch** [comment]
> Why define "numeric type"? Any type with a number is numeric. Standard comp sci.
Just randomly taking a random google for "numeric type": 
http://www.informit.com/articles/article.aspx?p=31344&seqNum=3
--> does not mention Boolean (is this a "numeric" or "logical" type?)

However this is not very important.

**Comment by andreas-junghanns** [comment]
This is a big fish, I hope that Torsten can check this tonight, else we merge it tomorrow morning.

**Comment by chrbertsch** [comment]
Closing as #799 was merged

**Pull request merged**
