### PR TITLE
Apply the changes to the specification documents proposed by MapleSoft

### PR DESCRIPTION
**Pull request by andreas-junghanns**

### CODE REVIEW

**Comment by t-sommer** [comment]
👍

**Comment by beutlich** [comment]
Please wait with new PRs and issues till Trac2GitHub succeeded. We already have a #1 as https://trac.fmi-standard.org/ticket/1.

**Comment by t-sommer** [comment]
The changes have been merged with 3b4cadc5de71ad41c497aa0892eb51a5d8e6396c

**Comment by beutlich** [comment]
FMI 3.0 only, right?

**Pull request closed without merging**
