### PR TITLE
Require implementation of all API functions

### LINKED ISSUE #1866: Clarify whether all constructor functions have to implemented
The FMI Spec states that 

> The FMU must implement all common API functions according to [Section 2.2](https://fmi-standard.org/docs/3.0/#general-mechanisms) and the functions for at least one of the interface types.

However the constructor functions (`fmi3Instantiate*()`) are all listed under "Common Functions" in [fmi3Functions.h](https://github.com/modelica/fmi-standard/blob/main/headers/fmi3Functions.h#L228)

```C
/***************************************************
Common Functions
****************************************************/

// ...

/* Creation and destruction of FMU instances */
FMI3_Export fmi3InstantiateModelExchangeTYPE         fmi3InstantiateModelExchange;
FMI3_Export fmi3InstantiateCoSimulationTYPE          fmi3InstantiateCoSimulation;
FMI3_Export fmi3InstantiateScheduledExecutionTYPE    fmi3InstantiateScheduledExecution;
```

even though they technically belong to the respective interface.

See also [#CATIA-Systems/FMPy/](https://github.com/CATIA-Systems/FMPy/issues/552).

### PR DESCRIPTION
**Pull request by t-sommer**
fixes #1866

### CODE REVIEW

**Comment by chrbertsch** [comment]
When we release FMI 3.1 with new API functions, this will have to be modified (in order that FMI 3.0 FMUs are valid FMI 3.1 FMUs) to something like

The FMU must implement all API functions declared in `fmi3Functions.h` or the `fmi3Functions.h` of a previous FMI 3.x release, even if they are only needed for interface types or optional capabilities that the FMU does not support.

**Comment by t-sommer** [comment]
Merging as decided by the Steering Committee.

**Comment by chrbertsch** [comment]
> ... but FMI 3.0 introduced a lot of new functions, rendering this all-implementation requires a bit hard.

Please note https://github.com/modelica/fmi-standard/pull/1873/files

**Comment by binghe** [comment]
> > ... but FMI 3.0 introduced a lot of new functions, rendering this all-implementation requires a bit hard.
> 
> Please note https://github.com/modelica/fmi-standard/pull/1873/files

Great, thanks!  Well, I was returning `fmi3OK` for those stub functions in my (generated) FMUs. Now I should modify them to return `fmi3Error` (before possibly logging actions) instead.  I'm glad to receive such fresh information from the FMI implementor point of view.

Regards,

Chun Tian
Fondazione Bruno Kessler (FBK), Italy

**Pull request merged**
