### PR TITLE
Serialization of array variables

### LINKED ISSUE #1187: Describe serialization of array only once and link everywhere else
From web-design meeting 21.09.2020.

### PR DESCRIPTION
**Pull request by klausschuch**
This PR should fix #1187 and partly #845 (the handling of string array variables is missing).

### CODE REVIEW

**Comment by klausschuch** [comment]
While checking the missing part about start elements for arrays of type fmi3String, I stumbled upon the missing minOccurs attribute. The default value of minOccurs is 1. Hence, there must be at least one start element element for each variable of type fmi3String.
This is problematic because there might be output strings without a start start string.

**Comment by andreas-junghanns** [comment]
> 
> 
> While checking the missing part about start elements for arrays of type fmi3String, I stumbled upon the missing minOccurs attribute. The default value of minOccurs is 1. Hence, there must be at least one start element element for each variable of type fmi3String.
> This is problematic because there might be output strings without a start start string.

For fmi3Strings, the Start value is an element, for other variable types, it is an attribute. Why?
For the minOccurs: Can´t we simply add it with 0?

**Comment by t-sommer** [comment]
> For fmi3Strings, the Start value is an element, for other variable types, it is an attribute. Why?

I think this is because Strings can contain spaces (unlike the other literals), so we can't use them as a separator (hence the separate elements).

**Comment by klausschuch** [comment]
Created PR #1241 to fix the xsd.

**Review by andreas-junghanns — APPROVED** [review]

**Pull request merged**
