### PR TITLE
Remove remnants of variability clock

### PR DESCRIPTION
**Pull request by clagms**
Fixes https://github.com/modelica/fmi-standard/issues/1441

### CODE REVIEW

**Review by t-sommer — APPROVED** [review]

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
You removed only "Clocks" from Table 19 - I think Table 20 has a similar issue.
Maybe you can merge my PR #1457 into this one?

**Comment by andreas-junghanns** [comment]
@clagms : Sorry to mess this PR up - I merged the one I created and @KarlWernersson approved.
You have a number of other (related?) changes in this PR, so I think it would be important to try and fix the current conflicts.

**Comment by clagms** [comment]
I think it's done now @andreas-junghanns . Thanks for spotting Table 20.

**Comment by clagms** [comment]
@andreas-junghanns , if you approve, then merge the PR.

**Review by andreas-junghanns — APPROVED** [review]

**Pull request merged**
