### PR TITLE
Define default variability

### LINKED ISSUE #1835: Default variability is missing for non-float non-clock non-clocked variables
The variability _attribute_ of the <fmi3Variable> elements is optional (see section 2.4.7.4).
When not present, table 17 specifies a default value for:
- variables of type `Float32` and `Float64`
- variables of type `Clock`
- clocked variables
In all other cases the default value is not defined.

### PR DESCRIPTION
**Pull request by chrbertsch**
resolves #1835

by deifing default variabiliy as "discrete" for varaibles of type other than float32 or float64

### CODE REVIEW

**Comment by chrbertsch** [comment]
@antvl , @pmai  and others: could you please review this, so that we can merge it?

**Review by andreas-junghanns — APPROVED** [review]
Looks ok, not sure it is complete.

**Review by pmai — APPROVED** [review]
Makes sense to me

**Comment by chrbertsch** [comment]
Design Webmeeting: 

Andreas: is this complete?
Pierre: It seemed to me to be complete. It covers all of he causalities. Clocks are not relevant here. 
Pierre: I checked it with table 18. This differs from the default value in FMI 2.0, where continuous did not make sense in many cases.
Andreas: OK

**Pull request merged**
