### PR TITLE
Disallow offset for inverse DisplayUnit

### LINKED ISSUE #1220: Allow inverse display units
Example: `mpg` (miles per gallon) as display unit for `L/100km` (liters per 100 km)

```xml
<UnitDefinitions>
  <Unit name="L/100km">
    <BaseUnit m="2" factor="1e-8"/>
    <DisplayUnit name="mpg" invert="true" factor="235.214583"/>
  </Unit>
</UnitDefinitions>
```

The display value `v_display` would be converted from the base value `v_base` as

```
v_display = factor * (1/v_base)
```

if `invert == true`.

### PR DESCRIPTION
**Pull request by chrbertsch**
resolves #1220

### CODE REVIEW

**Review by andreas-junghanns — APPROVED** [review]
This still feels kind of wrong. In A2L, MDF,... everywhere, inverse formulas for variables are allowed, without such restrictions.

**Review by t-sommer — APPROVED** [review]

**Review by KarlWernersson — COMMENTED** [review]
Opinions on how to do this seems to be quite diverse, 
Current formula is wrong so it need to be fixed.

I gave formula both for making it correct with offset and a proposal to fix the offset.
I am personally leaning to skipping it but I don't have a strong opinion in the matter

But since the diverging opinions should we step back and collect opinions?

alternative, I can approve the pull request and if someone wants offset for inverse units they can reopen it.

Should we have a statement why offset is not allowed for inverse units 
(could be its slightly more complicated and we don't see actual use case so we decided to ignore it)

**Comment by andreas-junghanns** [comment]
> alternative, I can approve the pull request and if someone wants offset for inverse units they can reopen it.

Agreed.
 
> Should we have a statement why offset is not allowed for inverse units
> (could be its slightly more complicated and we don't see actual use case so we decided to ignore it)

This would be needed. Can you add this to the PR?

**Comment by chrbertsch** [comment]
> >    Should we have a statement why offset is not allowed for inverse units
    (could be its slightly more complicated and we don't see actual use case so we decided to ignore it)

> This would be needed. Can you add this to the PR?

I added a sentence. Please review.

**Review by andreas-junghanns — APPROVED** [review]

**Comment by andreas-junghanns** [comment]
In case we ever meet a use case that requires this, we can easily drop this restriction.

**Review by KarlWernersson — APPROVED** [review]

**Pull request merged**
