### PR TITLE
Bump version to 3.0-alpha.5

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Comment by chrbertsch** [comment]
Shouldn't we mention the "alpha4" on the front page of the generated documentation?
grafik

**Comment by t-sommer** [comment]
Also, we should have made these changes _before_ tagging the alpha release...

**Comment by t-sommer** [comment]
@pmai, should we move the `v3.0-alpha.4` or create a `v3.0-alpha.5` soon?

**Comment by t-sommer** [comment]
@pmai, can you please review this PR?

**Comment by nickbattle** [comment]
@t-sommer Should this PR include a nudge to the Reference-FMUs commit so that their types are like Float64Type rather than Float64?

**Comment by t-sommer** [comment]
> @t-sommer Should this PR include a nudge to the Reference-FMUs commit so that their types are like Float64Type rather than Float64?

I'm just updating the Reference FMUs

**Comment by nickbattle** [comment]
I'm getting a few errors on the (new) reference FMUs. Can you check?
```
---------------------- Clocks/FMI3.xml
Checking XML
2.2.8 Variable "inClock3" causality/variability/initial/start <input>/<clock>/<exact>/nil invalid at line 16
2.2.8 Variable "inClock3" initial/variability/start <exact>/<clock>/nil invalid at line 16
2.2.8 Variable "inClock3" invalid at line 16
2.2.8 Variable "input2" causality/variability/initial/start <input>/<discrete>/nil/nil invalid at line 24
2.2.8 Variable "input2" invalid at line 24
2.2.1 Variables invalid
2.2.9 Outputs section does not match output variables at line 28
2.2.9 InitialUnknowns must include refs: {1004, 1005, 2001, 2002, 2003, 2004, 2005, 2007}
Errors found.

---------------------- Feedthrough/FMI3.xml
Checking XML
2.2.9 InitialUnknowns must include refs: {3, 5, 7, 9, 12}
Errors found.
```

**Pull request merged**
