### PR TITLE
Merge BCS and HCS

### PR DESCRIPTION
**Pull request by andreas-junghanns**
a lot still to be done towards #1077

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
Torstens: Can you both have a look? Now that I see the change, I think merging HCS and BCS is a must: the text simplifies, the understanding is greatly improved, much of the strange differentiation between the different CS types simply goes away.

**Comment by chrbertsch** [comment]
Now that BCS and HCS are called "Co-Simulation", I consider it strange that we talk about "Scheduled Co-Simulation" (abbreviations CS and SCS). Shouldn't we call it differently  (also with a two-letter abbreviation)?
The two-letter abbreviation of "Scheduled Simulation" is not good, so what about "partitioned simulation" (PS), as the "activate model partition" is the fundamental method of this kind of FMI?
Then we would have abbreviations ME, CS and PS.

**Comment by t-sommer** [comment]
I would still prefer "Scheduled Execution" (SE), as it was call originally.

**Comment by andreas-junghanns** [comment]
Web design meeting:
AndreasJ: I like the document improvement: it is simpler and easier to read, in general much better. But: Is something lost in functionality that we wanted to add for HCS?
Result: all agree this merge is better and doable. Improvement suggestion:
Clarify:
 - FMU must be able to signal about not caring about events (do not call enterEventMode)
 - event mode immediately after initialization (and after ReconfigurationMode, see next) with Early Return from doStep()
    Early Return after dt==0.0 is possible. The master should call with dt > 0.0.
 - ReconfigurationMode will be reachable directly from StepMode.
Masoud: now the ME and CS state machines are not symmetric anymore and wrapping a ME in CS will be hard.
Pierre: But the simplification is worth the change in CS, preferred over symmetry. But even if we have it asymetric, it can be handled by auto-transitions.
Andreas: Do we want to keep ME 3.0 similar to ME 2.0?
Pierre: We should have this discussion about state transitions in a separate issue.
All: Agree that this merge is a step forward and should be followed as outlined above.

**Comment by andreas-junghanns** [comment]
I addressed all open point we discussed at the meeting today.

Please someone else check the changes and overall state.

Missing:
 - xsd images (Torsten wanted to fix a few other things before this makes sense)
 - We still pull a code snippet with s1_fmi3InstantiateBasicCoSimulation from ReferenceFMUs/examples/co-simulation.c

**Comment by t-sommer** [comment]
These should not hold us back
 
> * xsd images (Torsten wanted to fix a few other things before this makes sense)

Is pure XSD cosmetics.

> * We still pull a code snippet with s1_fmi3InstantiateBasicCoSimulation from ReferenceFMUs/examples/co-simulation.c

Will be updated once this PR is merged.

**Comment by andreas-junghanns** [comment]
> Small suggestion: shouldn't we in the overview table 1 of 1.2.4. mark clocks (and additionally events) in CS as optional?

Currently, "optional" is not communicated at all (just available or not). We could extend the cells to also allow for "optional" entries.

Another issue with this table is the "solver included" for Scheduled Execution: Strictly this is not true in two ways: "Solver" for controller code has no meaning and should be called "scheduler". And the scheduler is clearly NOT included, that is the feature.

**Pull request merged**
