### PR TITLE
Generate schema figures in CI

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Review by chrbertsch — COMMENTED** [review]
Looks good! 
Could you please add the generation of the graphical view of the BuildConfiguration xsd?

**Review by chrbertsch — COMMENTED** [review]
Hi @t-sommer, thanks for adding the generation of the BuildConfiguration picture.
But fmiBuildDescription.png is not part of the commit
(Is it possible to inspect the generated html documentation  for a branch /pull request? I think this has changed since we changed from CircleCI to github actions, right?

**Comment by t-sommer** [comment]
see https://github.com/modelica/fmi-standard/actions/runs/3339862620
At the bottom you can download the artifacts.

**Comment by chrbertsch** [comment]
Thanks

> see https://github.com/modelica/fmi-standard/actions/runs/3339862620
> At the bottom you can download the artifacts.

Thanks!

As https://github.com/t-sommer/fmi-standard/tree/generate-figures-windows/docs/images/schema is empty, this commit will remove the generated schema pictures from the repo. This is fine for the html generation with GithubActions, but local docu generation is then no longer possible, right?

**Comment by t-sommer** [comment]
To get the schema PNGs you can run the script (see contributing.md) or copy them from an existing build.

**Review by chrbertsch — APPROVED** [review]

**Pull request merged**
