### PR TITLE
rename scheduled co-simulation to scheduled execution in overview picture

### PR DESCRIPTION
**Pull request by chrbertsch**

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
Was the alpha channel removed by design or rather as side-effect?

**Comment by chrbertsch** [comment]
@beutlich : I do not get it: what do you mean with "alpha channel"

**Review by andreas-junghanns — APPROVED** [review]

**Comment by beutlich** [comment]
> 
> 
> @beutlich : I do not get it: what do you mean with "alpha channel"

Sorry, you can see in the rich diff that the background transparency is gone. Not sure, if relevant or not.

grafik

**Comment by chrbertsch** [comment]
> Sorry, you can see in the rich diff that the background transparency is gone. Not sure, if relevant or not.

Ah, ok thanks. I did not change it intentionally. @t-sommer : is this important?

**Review by t-sommer — APPROVED** [review]

**Pull request merged**
