### PR TITLE
Update logging documentation

### LINKED ISSUE #1434: Backport clarifications in logging documentatoin to FMI2.0.x
see https://github.com/modelica/fmi-standard/pull/1432

### PR DESCRIPTION
**Pull request by t-sommer**
see #1432, fixes #1434

### CODE REVIEW

**Comment by chrbertsch** [comment]
Hi @t-sommer , 
Thank for proposing the changes.

Could you please make the changes in https://github.com/modelica/fmi-standard/blob/support/v2.0.x/docs/2_1_common_api.adoc so that we can use the github machinery to diff and review the changes?
Until now, the working mode to bring changes to 2.0.x versions was to do the changes in adoc in PRs, and after merging I ported them to the .doc document in https://github.com/modelica/fmi-design/tree/master/FMI_2.0.3

Where did to take the .doc from? Was it the latest version from https://github.com/modelica/fmi-design/tree/master/FMI_2.0.3

**Comment by t-sommer** [comment]
> Where did to take the .doc from?

Yes.

> If the *.doc is the source of truth, why do we maintain the *.adoc files?

**Comment by chrbertsch** [comment]
> > Where did to take the .doc from?
> 
> Yes.

From where? https://github.com/modelica/fmi-design/tree/master/FMI_2.0.3?  We could decide to change the storage location of the .doc to https://github.com/modelica/fmi-standard/tree/support/v2.0.x/docs , but we should not have multiple storage locations of  the .doc

> 
> If the *.doc is the source of truth, why do we maintain the *.adoc files?

The idea is to use the machinery of PRs as for FMI3 development. Since FMI 2.0.1 I have been porting the changes of accepted PRs to the .doc after the PRs got accepted.

**Comment by chrbertsch** [comment]
@t-sommer : I put your changes into the adoc and ported them to the .doc from fmi-design/FMI2.0.3
Could you please check? Thanks!
(in the future, the .doc in the branch support/v2.0.x shall be "source of truth" for 2.0.x bugfix releases.
The adoc is used only to propose and discuss changes bofore they are ported to the .doc)

**Review by chrbertsch — APPROVED** [review]

**Comment by t-sommer** [comment]
@chrbertsch, please update the .docx in a separate PR and make sure it also contains the previous changes (if any).

**Review by chrbertsch — APPROVED** [review]

**Review by andreas-junghanns — APPROVED** [review]
There are so many formatting issues in this text, I think we should make an effort before releasing 2.0.3.

**Comment by chrbertsch** [comment]
> ...  I think we should make an effort before releasing 2.0.3.

I think it is not worth doing this effort adoc, any 2.0.x release will be based on the word document, see #1438

**Pull request merged**
