### PR TITLE
add abbreviations for FMI interface types 

### PR DESCRIPTION
**Pull request by chrbertsch**
according to discussion in #728

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
I agree with the two letter abbreviations. But I know Torsten thinks that 3-letters might be better.
Torsten: How strong is your opinion here?

**Comment by t-sommer** [comment]
I'm for "HCS" and "SES". I find it strange to have the "Simulation" in "CS" but not in "HC" and "SE".

**Comment by t-sommer** [comment]
@andreas-junghanns and @chrbertsch, if this is okay with you, I'll update the PR.

**Comment by chrbertsch** [comment]
@t-sommer : fine for me,  I even like your proposal better, e.g. to show the relation between CS and HCS. 
And the the two new types get introduced in FMI 3, so they deserve 3 letters :-)

**Pull request merged**
