### PR TITLE
Explain qualifier values

### PR DESCRIPTION
**Pull request by andreas-junghanns**

### CODE REVIEW

**Review by masoud-najafi — APPROVED** [review]
What would be qualifier value at the very first invocation of fmi3GetIntervalDecimal()? fmi3IntervakUnchanged would mean unchanged WRT the value in XML ?

**Comment by andreas-junghanns** [comment]
> 
> 
> What would be qualifier value at the very first invocation of fmi3GetIntervalDecimal()? fmi3IntervakUnchanged would mean unchanged WRT the value in XML ?

That would be a reasonable assumption, I suppose. This is different though for non-periodic clocks that have no default in the XML - see your other ticket.

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz : pushed both PRs now, please check

**Review by TorstenBlochwitz — APPROVED** [review]
Much better now.

**Pull request merged**
