### PR TITLE
add statement to explicitly forbid changes in the xml

### PR DESCRIPTION
**Pull request by chrbertsch**
according to discussion in #387

### CODE REVIEW

**Comment by chrbertsch** [comment]
I was not sure whether 2.2 or 2.3 is the right place for statement; here it is in 2.2 dealing with the xml. One could also argue that changing modeldescription.xml takes place within the zip file, which would be in 2.3.  Please comment.

**Comment by andreas-junghanns** [comment]
I am not sure if we should have two places where we point this out. But if in doubt, two are better, right? Should we make one into a non-normative text?

**Comment by andreas-junghanns** [comment]
> I was not sure whether 2.2 or 2.3 is the right place for statement; here it is in 2.2 dealing with the xml. One could also argue that changing modeldescription.xml takes place within the zip file, which would be in 2.3. Please comment.

Thematically, both sections would work, but I would not know where to place this in 2.3 - so your choice seems more natural. And earlier is likely better than later in the document.

**Comment by andreas-junghanns** [comment]
I should have submitted this as draft - and I have no idea how to get this into the draft status.

**Comment by chrbertsch** [comment]
> I would put the statement in 2.3 if it was only in one location - 2.2 is concerned with the schema, not the purpose of the file. But both would be fine.

This brings us to the question whether we in 2.3 should more generally describe what ist allowed to change in an FMU
* modeldescription.xml --> no!
* source directory --> no?
* binaries --> new platform binearies may be added, others removed?
* documentation -->information might be added? existing documentation be changed?
* resources: ? Might e.g. characteristic map files stored in resources be changed/exchanged?
* extra --> yes! as specified

**Comment by pmai** [comment]
> This brings us to the question whether we in 2.3 should more generally describe what ist allowed to change in an FMU

There is no support for changing any content of an FMU, with the sole exception of the extra directory entries.

This obviously does not mean that you cannot modify stuff inside an FMU when you know what you are doing and the circumstances warrant it, but there is no support for this and no requirement on FMU generators to enable such things...

I.e. rewriting the modelDescription.xml by e.g. removing variables works, because there is no way for the FMU or the importer to even find out about this, so for them this is a valid transformation. Nevertheless there is no support in the standard for this and no warranties are spelt out. And e.g. an FMU signing scheme might prevent this from occurring and thus break this transformation.

In general I don't think we should worry about this or spell out too much on this, since it only leads to confusion.

The special case of start values warrants additional language not because this wasn't clear already, but because we have seen common misuse in the wild, and thus should be explicit.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

@andreas-junghanns : I will merge it.

**Pull request merged**
