### PR TITLE
Re-add steps to build spec with Ruby and AsciiDoctor gem

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Comment by t-sommer** [comment]
@KarlWernersson can you check if this works for you?

**Comment by KarlWernersson** [comment]
I also had to install RubyGems to be able to install the asciidoctor gem
Its found at this location
https://rubygems.org/pages/download

**Comment by t-sommer** [comment]
@KarlWernersson did you install the RubyInstaller w/o DevKit?

**Comment by KarlWernersson** [comment]
rubyinstaller-devkit-2.5.3-1-x64.exe

**Comment by t-sommer** [comment]
The `gem` command should come with DevKit. Is it possible that you just didn't add it to the path and the separate installation of RubyGems fixed this problem?

**Comment by KarlWernersson** [comment]
Possible, first time with ruby...

**Comment by t-sommer** [comment]
Can you approve the PR and re-open the issue if the problem pops up again?

**Pull request merged**
