### PR TITLE
Update 2_2_common_schema.adoc

### PR DESCRIPTION
**Pull request by masoud-najafi**
Connection of variables with variability clock #1126

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
@masoud-najafi : Please check my change proposals.

**Review by masoud-najafi — COMMENTED** [review]
I do not understand this "the importer generates the clock signal.".  
I understand things in this way: the importer does not generate itself any clock signal, a clock signal is generated by outputClock of an FMU and the importer just transmits it to the inputClock of anther FMU. This is very similar to the regular inputs: the importer does not generate a signal by itself.

**Comment by andreas-junghanns** [comment]
> 
> 
> I do not understand this "the importer generates the clock signal.".
> I understand things in this way: the importer does not generate itself any clock signal, a clock signal is generated by outputClock of an FMU and the importer just transmits it to the inputClock of anther FMU. This is very similar to the regular inputs: the importer does not generate a signal by itself.

An importer that wants to run a single FMU must generate clocks to trigger functionality inside the FMU.
This is trivial for periodic clocks, right?
It could even do that for a-periodic clocks, asking the human operator about when to trigger such clocks.
In any case, it is not required, that another FMU is involved to trigger input clocks.

**Comment by masoud-najafi** [comment]
So Actually, the importer creates a fictitious FMU with an outputClock that generates the clock ticks. We have had this kind of behavior with FMUChecker that creates input signals to the FMU out of an CSV file. 
IMHO, this is very specific to the importer, and may not bring into the standard. The FMU should stay agnostic of who is creating the clock ticks.

**Comment by andreas-junghanns** [comment]
> 
> 
> So Actually, the importer creates a fictitious FMU with an outputClock that generates the clock ticks. We have had this kind of behavior with FMUChecker that creates input signals to the FMU out of an CSV file.
> IMHO, this is very specific to the importer, and may not bring into the standard. The FMU should stay agnostic of who is creating the clock ticks.

But you are proposing a text where it seems that an FMU is mandatory and write it as if no other way is allowed.
I think this must be clearly stated.

**Comment by masoud-najafi** [comment]
OK. I got your point. What I am just proposing is to avoid connection between Clock and non-Clock ports. If the input-clock port is left unconnected (which is allowed in the text), then the importer can do what it wants with it, like sending periodic ticks.

**Pull request merged**
