### PR TITLE
Use bool from stdbool.h instead of _Bool

### LINKED ISSUE #1350: _Bool is not defined
Hi

I tried to compile my FMUs with alpha6. I was not able to compile with g++ on ubuntu (version 9.3) because _Bool is not defined.
It is used for fmi3Boolean and fmi3Clock in fmi3PlatformTypes.h

### PR DESCRIPTION
**Pull request by t-sommer**
fixes #1350

### CODE REVIEW

**Review by andreas-junghanns — APPROVED** [review]
I am sure this is much better.
I still do not like that clocks are also boolean - just saying, does not belong here.

**Review by pmai — APPROVED** [review]
Probably simplest approach, even if it pollutes the global namespace some more.

**Comment by andreas-junghanns** [comment]
@t-sommer : can we still treat this as Alpha.6?

**Comment by t-sommer** [comment]
v3.0-alpha.6 has already been tagged, so I would say no. However existing implementations should be API compatible.

**Pull request merged**
