### PR TITLE
Prepare v2.0.5 rc1

### LINKED ISSUE #1987: Create FMI 2.0.5RC1 prerelease
- [x] Update copyright year in standard text, headers schema
- [x] Create PDF with changemarks
- [ ] Create text for prerelease

### PR DESCRIPTION
**Pull request by chrbertsch**
resolves #1987

### CODE REVIEW

**Comment by beutlich** [comment]
There is a blank missing after the version:

grafik

**Comment by chrbertsch** [comment]
> There is a blank missing after the version:
> 
> grafik

Fixed in the latest uploaded PDFs. Thanks!

**Review by t-sommer — CHANGES_REQUESTED** [review]
- The release candidate should not have the "RC" suffix in the document as we will only rename the file once it's reviewed and approved.
- The hyperlink in A.3.8 should be blue for consistency.
- The document `FunctionalMockupInterface_2.0.5-RC1_with_changemarks.pdf` is missing the red change marks of the [previous version](https://github.com/modelica/fmi-standard/releases/download/v2.0.4/FMI-Specification-2.0.4-with-changemarks.pdf).

**Comment by t-sommer** [comment]
I've added the PDFs to https://github.com/modelica/fmi-standard/releases/tag/v2.0.5-rc.1.

**Pull request closed without merging**
