### PR TITLE
Bump version to 3.0-beta.2

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Review by chrbertsch — COMMENTED** [review]
Will the "beta.2" be includedin the generated html, or will this be done afterwards?
Currently it contains the commit hash and looks  like
grafik

**Comment by t-sommer** [comment]
> Will the "beta.2" be includedin the generated html

Yes. This happens automatically for tagged commits.

**Review by chrbertsch — APPROVED** [review]

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
I searched for "beta\.1" and found the example files still contain the that. OK?

**Comment by t-sommer** [comment]
> I searched for "beta.1" and found the example files still contain the that. OK?

Did you update the "Reference FMUs" submodule?

**Comment by andreas-junghanns** [comment]
Not in Reference-FMUs, but in ...\fmi-standard\docs\examples

**Comment by t-sommer** [comment]
> Not in Reference-FMUs, but in ...\fmi-standard\docs\examples

Which file?

**Review by andreas-junghanns — APPROVED** [review]

**Pull request merged**
