### PR TITLE
Clarify clocks

### PR DESCRIPTION
**Pull request by clagms**
Ongoing work on:
- https://github.com/modelica/fmi-standard/issues/1000
- https://github.com/modelica/fmi-standard/issues/1071
- https://github.com/modelica/fmi-standard/issues/1073
- https://github.com/modelica/fmi-standard/issues/1066
- https://github.com/modelica/fmi-standard/issues/916
- https://github.com/modelica/fmi-standard/issues/723

since these all seem to span from the same source: confusion around the meaning of clocks.

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
@clagms : Can we discuss this today to advance this? I am sure we all want to have this clarification rather sooner than later...

**Comment by clagms** [comment]
Yes that would be great @andreas-junghanns !

**Comment by andreas-junghanns** [comment]
@clagms : your PRs are getting more and more outdated - are you planning on giving them up, or will your finish them?

**Comment by clagms** [comment]
Deleting this PR as it is too big. I've made the introduction in https://github.com/modelica/fmi-standard/pull/1143
Still need to go over the open questions before attempting to progress here.

**Pull request closed without merging**
