### PR TITLE
Fix hard coded refs (#672)

### PR DESCRIPTION
**Pull request by andreas-junghanns**

### CODE REVIEW

**Comment by chrbertsch** [comment]
In 2_1_common_api.adoc we have "see remark 3".  Shall we add an anchors to this remark and link to it?

**Comment by andreas-junghanns** [comment]
> 
> 
> In 2_1_common_api.adoc we have "see remark 3". Shall we add an anchors to this remark and link to it?

I could not find this reference. Was that fixed in the meantime?

**Comment by chrbertsch** [comment]
> I could not find this reference. Was that fixed in the meantime?

Ah, it seems to be in 3.1.1.
grafik

**Comment by andreas-junghanns** [comment]
The remarks are all manually labeled in the text, so referencing the remark with a fixed reference seems safe, right?

**Pull request merged**
