### PR TITLE
Add "h" and rename "z" to "b" in data flow figures

### LINKED ISSUE #1422: Wrong labels on overview data-flow images
I was reading the latest dev version of the FMI 3.0 spec (from  https://fmi-standard.org/docs/3.0-dev/#_overview, commit https://github.com/modelica/fmi-standard/commit/02bef77cf908940182099e59be73759018aa6758):

schemes

and I noticed the following aspects that are not clear to me in Section 1.2.1, 1.2.2 and 1.2.3 (that I was not able to find tracked in any open issue or PR):

1. **z** is used to indicate both *even indicators* and *hidden states*, but given the symbol defined in https://fmi-standard.org/docs/3.0-dev/#mathematical-definitions I guess *hidden states* should be indicated with **b** .
2. In section 1.2.2, the variable **h** (communication step size) is not explained with a short description, as the other variables in the scheme.

### PR DESCRIPTION
**Pull request by t-sommer**
fixes #1422

### CODE REVIEW

**Review by chrbertsch — CHANGES_REQUESTED** [review]
Looks good, but we still have to 
- either  change the description of the hidden states **b** in 2.1 so that these hidden states are not only present in ME but also in CS (and SE?
- or remove move them in the CS (and SE?) figures
In the SE figure, the problem also exists: **z** are used within the model partitions both for event indicators and hidden states. But there the event indicators for me do not really makes sense. wouldn't it be better to remove them there, as they are misleading?

**Comment by traversaro** [comment]
Thanks @t-sommer . I think the problem that z refers to both event indicators and hidden states is present also in section 1.2.3, i.e. i in image `scheduled-execution-data-flow.svg` .

**Comment by traversaro** [comment]
> Thanks @t-sommer . I think the problem that z refers to both event indicators and hidden states is present also in section 1.2.3, i.e. i in image `scheduled-execution-data-flow.svg`

Actually this was already reported by @chrbertsch comment.

**Comment by andreas-junghanns** [comment]
> 
> 
> Looks good, but we still have to
> 
>     * either  change the description of the hidden states **b** in 2.1 so that these hidden states are not only present in ME but also in CS (and SE?
> 
>     * or remove move them in the CS (and SE?) figures
>       In the SE figure, the problem also exists: **z** are used within the model partitions both for event indicators and hidden states. But there the event indicators for me do not really makes sense. wouldn't it be better to remove them there, as they are misleading?

Since "b" appears in the mathematical descriptions of states in all three interface types (e.g. Initialization Mode is common to all of the interface types), this needs to be in the image for all three of them.

I fixed the SE image.

I think this is now good and should be merged if all agree.

**Review by andreas-junghanns — APPROVED** [review]

**Review by chrbertsch — APPROVED** [review]
I mad a change so that hidden states **b** adress also SE and CS. @t-sommer : OK?

**Review by andreas-junghanns — APPROVED** [review]

**Pull request merged**
