### PR TITLE
Fixes clock interval part of #1663

### PR DESCRIPTION
**Pull request by KarlWernersson**

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
Note: images do not need regeneration as the XSD change only effects values of the attribute `intervalVariability` of clocks which do not show in the diagram(s).

**Review by andreas-junghanns — APPROVED** [review]
@KarlWernersson : I made a few minor corrections, please check that I did not invalidate any of your changes!

**Review by andreas-junghanns — COMMENTED** [review]
I would remove both sentences saying: `This attribute cannot be combined with intervalDecimal.`
If I remember correctly, the fractions mechanic was purely optional, and now we seem to make it mandatory if an FMU supports only that. Of course it is easy to use the fractions and build decimals from that. But should we enforce this?

**Comment by KarlWernersson** [comment]
that fractional is still optional is not a problem. the problem i see is if you give both a fractional and a decimal stat value. Which one to use? What if they are not the same, if 1/3 is used they cannot be the same. if fractional is given an the importer want to use decimal it is an easy computation to round a fractional to a decimal the other way around is not. 
So I am not trying to prevent decimals, just that both decimal and fractional start values are given. I want to preserve single source of truth.

Most cases this will not pose a problem but if someone want sot synchronize a clock of 1/3 and one of 2/3 in decimals that's up to them. Maybe use setIntervalDecimal to select a more appropriate one for decimal computations.

**Comment by andreas-junghanns** [comment]
I think the decimals are less accurate than the fractions, except fractions are bit more difficult to handle for exporters and importers. So if both are given, you should use fractions if you know how (the Truth), otherwise the decimals are good approximations.
This would be good enough for the majority of all importers and for those that need more, they will insist on fraction definitions in the FMUs they import.

To you other points: To synchonize clocks that tick every 1/3 and 2/3 of a second should not be done using these numbers: it should be done internally in the FMU.

**Comment by KarlWernersson** [comment]
What i am trying to say is that you cannot give a start value both in fraction and in decimal. The FMU must give one just as for constant, that does not prevent the master to set a different value either by fraction or by decimal if it supports both but we can only have one start value not two.

**Comment by KarlWernersson** [comment]
OK but I don't think this is entirely true.

For constant intervalVariablity the exporter is limited to choose fractal or decimal representation it can't choose both.
Similar the start value for the clock interval for a fixed or a tunable describes the default value for the clock if the importer does not call setInterval on that clock. I would assume that such a clock would behave the same as a constant variability clock.

Now if we allow both decimal and fractal start values at the same time we have 2 scenarios.

1 They match. 
2. They dont match.

If 1 no problem

2 thye could missmatch due to error ie. 0.5 != 1/5
 they mismatch due to roundoff error 1/7-0.14 ~= 0.0029

By preventing the FMU from giving a start value in both decimal and fraction at the same time we avoid a lot of potential problems.

Now my idea was to enforce fractional if if supports it to make it easy to explain. But I don't see a need to enforce this I am fine that an FMU that supports fractional export decimal. Thinking on it it is probably better as it should reflect what the model exporter has selected.

But I am convicted that if we allow the xml to print a start value for both decimal and fractional at the same time for the same clock, we invite errors.

**Review by andreas-junghanns — APPROVED** [review]

**Comment by t-sommer** [comment]
Superseded by e88d1e251c088fb8d09bdaac40dabef354895a56.

**Pull request closed without merging**
