### PR TITLE
Scheduled Execution Example

### PR DESCRIPTION
**Pull request by MBlesken**
@IZacharias and I have created an example for Scheduled Execution. I would hereby like to invite @andreas-junghanns @t-sommer, @clagms and others to leave review comments. 

A first draft try was PR #1087. A discussion started on the pseudo code and Reference-FMUs. I would like to propose the adjustments of this PR as a compromise. The examples' intention is to focus on the crucial peculiarities of the SE. While there is a compilable example in the reference-FMUs as well we rate it to be too excessive to include it into the specification even when limited to particular sections. But still feel free to comment on that as well.

### CODE REVIEW

**Comment by t-sommer** [comment]
Can you integrate your code into one of the existing examples in the Reference FMUs and include it from there (instead of using pseudo-code snippets)?

**Review by IZacharias — APPROVED** [review]

**Comment by andreas-junghanns** [comment]
All: We recently changed the signature of fmi3IntermediateUpdateCallback and fmi3DoStep and moved how to signal that a clock ticket to the return value of fmi3DoStep clocksTicked. See #1127.

@t-sommer : How do we communicate clocksTicked from the FMU to the master during fmi3ActivateModelPartition()?
We might have missed this in our discussion of #1127.

**Comment by MBlesken** [comment]
@andreas-junghanns As agreed I again took a close look on the Reference-FMUs code in order to evaluate its usability to explain a SE. Here is an example that I think points out very clearly why pseudo code is more convenient to pursue the intention of focusing on the crucial peculiarities of the SE in the specification document as opposed to the platform-specific implementation in Reference-FMUs:

**Master implementation to invoke the execution of a task in  …\Reference-FMUs\examples\scs_threaded.c**

fmi3Status cb_intermediateUpdate(fmi3InstanceEnvironment instanceEnvironment,
    fmi3Float64 intermediateUpdateTime,
    fmi3Boolean eventOccurred,
    fmi3Boolean clocksTicked,
    fmi3Boolean intermediateVariableSetAllowed,
    fmi3Boolean intermediateVariableGetAllowed,
    fmi3Boolean intermediateStepFinished,
    fmi3Boolean canReturnEarly) {

    fmi3Instance *fmu = ((fmi3Instance*)instanceEnvironment);

    HANDLE thr_handle;
    int returnval;
    // Local copy for this thread of the states of the output clocks
    fmi3Clock localOutputClocks[N_OUTPUT_CLOCKS];

    // In this example we only check for ticking output clocks.
    if (!clocksTicked) {
        logEvent(fmu, "No clock active in intermediateUpdate callback");
        return fmi3OK;
    }

    // In order to be threadsafe we have to check the clocks under lock
    // and copy their states
    GlobalLock(globalLockVar);
    if (!checkOutputClocks(fmu)) {
        GlobalUnlock(globalLockVar);
        logEvent(fmu, "No clock active in intermediateUpdate callback");
        return fmi3OK;
    }
    for (int oc = 0; oc < N_OUTPUT_CLOCKS; oc++) {
        localOutputClocks[oc] = outputClocks[oc];
    }
    GlobalUnlock(globalLockVar);

    // Some output clock ticked, check for dependend input clocks and, if there are any, fire them
    // input clock 3 depends on output clock 1
    // This dependency is taken from ModelDescription.xml
    if (localOutputClocks[IDX_OUT_CLOCK1]) {
        // create a thread that will run the model partition for input clock 3
        logEvent(instanceEnvironment, "cb_intermediateUpdate starting thread for input clock 3 (vr=%d)", vr_inClock3);

        iu_arguments.comp = instanceEnvironment;
        iu_arguments.clockRef = vr_inClock3;
        iu_arguments.retval = &returnval;
        iu_arguments.activationTime = time;
        thr_handle = (HANDLE)_beginthreadex(NULL, 0, thr_activateModelPartition, &iu_arguments, 0, NULL);
        if (thr_handle != NULL) {
            // Bind the thread to the designated processor
            SetThreadAffinityMask(thr_handle, processorMask);
            // Set the designated priority
            SetThreadPriority(thr_handle, inputClockPrio[IDX_IN_CLOCK3]);
        }
        else {
            logEvent(instanceEnvironment, "Could not create thread in cb_intermediateUpdate");
        }

    }
    …
    return fmi3OK;
}


**Master implementation as proposed for index.html#example-scheduled-execution**

void CallbackIntermediateUpdate(..., fmi3Boolean clocksTicked, ...) 
{
    fmi3ValueReference outputClockReferences = {7};
   fmi3Boolean[] clocksActivationState = {fmi3ClockInactive};
   if (clocksTicked)
   { 
      // ask FMU if output clock has ticked
      fmi3GetClocks(... outputClockReferences, &clocksActivationState, ...); 
   } 
   if (clocksActivationState[0])
   { 
     // schedule task for AperiodicClock
      Scheduler->ScheduleTask(TaskAperiodic); 
   }
}

**Review by andreas-junghanns — APPROVED** [review]
Agreed @MBlesken - this is too much detail and anyone interested can have it in the reference FMU, no need to repeat it as example in the standard text. Let´s leave things as you proposed.

**Pull request merged**
