### PR TITLE
Add intro synchronous clocks

### PR DESCRIPTION
**Pull request by clagms**
Adds the introductory text described in https://github.com/modelica/fmi-standard/issues/1073

### CODE REVIEW

**Review by andreas-junghanns — APPROVED** [review]
I like it - brief intro with problem description and example.
Can we build this example in the Reference FMUs as examples?

**Comment by andreas-junghanns** [comment]
Do you think you want to enhance this further and keep it in draft state?
When you think you are done, please mark as "ready for review".

**Comment by clagms** [comment]
> Can we build this example in the Reference FMUs as examples?

Good idea. This would also validate the explanation. I've created https://github.com/modelica/fmi-standard/issues/1150 to keep track of this.

**Comment by andreas-junghanns** [comment]
@masoud-najafi , @TorstenBlochwitz : can either of you read through the PR? I would like at least one more person to share the blame ;)

**Review by masoud-najafi — COMMENTED** [review]
In 2_2_common_schema.adoc  I cannot understand the following phrase, is it related to SE or the TriggeredBy attribute?

If <<causality>> = <<output>> and <<variability>> = <<clock>> the <<outputClock>> tick event can occur only in the model partition that is related to the referenced <<inputClock>>, i.e. the <<outputClock,`output clock`>> value (active/inactive) can only change in this model partition.

**Comment by andreas-junghanns** [comment]
> In 2_2_common_schema.adoc I cannot understand the following phrase, is it related to SE or the TriggeredBy attribute?
> 
> If <> = <> and <> = <> the <> tick event can occur only in the model partition that is related to the referenced <>, i.e. the <<outputClock,`output clock`>> value (active/inactive) can only change in this model partition.

This sentence is not part of this PR. Can you open another a new issue for this?
If this is the only problem you have with this PR, do you approve?

**Review by masoud-najafi — APPROVED** [review]

**Pull request merged**
