### PR TITLE
Update docs for new GitFlow branching scheme

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Comment by chrbertsch** [comment]
Looking at the picture:
is 3.x really a support branch?  Should be 3.x.y in my view

**Review by chrbertsch — APPROVED** [review]

**Review by andreas-junghanns — APPROVED** [review]

**Comment by pmai** [comment]
Did I miss the rationale for switching to gitflow again?

**Comment by chrbertsch** [comment]
> 
> 
> Did I miss the rationale for switching to gitflow again?

See discussion in https://github.com/modelica/fmi-standard/issues/1317 and Steering Committe meeting: https://github.com/modelica/fmi-design/tree/master/Meetings/2021/2021-03-02-FMI-Steering#2-using-gitflow-branching-scheme

**Comment by pmai** [comment]
Sorry that I missed this, but #1337 (and the steering meeting minutes) does not provide any rationale for switching development workflows, because the auto-publishing problem could just as easily have been fixed by not using master/main for the auto-publishing, which would only affect the CI scripts and release publishing, whereas the new development workflow now affects all developers (including down-stream developers) just to fix, it seems, a simple CI issue. This seems not good to put it mildly, especially in between releases. Probably has sailed, but let's maybe not have impactful process decisions to fix simple technical problems at very short notice in the future?

**Comment by chrbertsch** [comment]
@pmai : What are your arguments against using the Gitflow branching scheme?
Can we discuss this in the regular webmeeting on Wednesday?
There are (unfortuneately) few people creating and working with PRs, and even fewer digging as deep into the git subtleties like @t-sommer  and you, so we should come to an acceptable solution for them

**Comment by t-sommer** [comment]
I guess the whole discussion boils down to two questions that caused confusion in the past:

- should the development version be "customer facing"?
- should we do the release engineering on the main development branch (currently `master`)?

If the commit / tag added to the HTML in 369ec990b08392bd4773fef9080bfe97d363df99 solves this problem we can close this PR.

**Comment by chrbertsch** [comment]
> should the development version be "customer facing"?

We should then link on https://fmi-standard.org/  and https://github.com/modelica/fmi-standard link not only the latest development version but more prominently the latest tagged version


> should we do the release engineering on the main development branch (currently master)?

Even with using Gitflow, we could the release preperation on an extra branch, right?

**Comment by t-sommer** [comment]
> Even with using Gitflow, we could the release preperation on an extra branch, right

Either way all contributions should be made via PRs.

**Pull request closed without merging**
