### PR TITLE
Scheduled Co-Simulation Pseudo Code Example incl. graphic

### PR DESCRIPTION
**Pull request by MBlesken**
@IZacharias and I are starting to create an example to explain the scheduled co-simulation. @t-sommer @andreas-junghanns @clagms @chrbertsch please comment on this DRAFT contribution. Meanwhile we will continue to improve the text around the pseudo code and graphic. Thank you.

### CODE REVIEW

**Comment by t-sommer** [comment]
Please move any example code to the Reference FMUs repo and include it from there.

**Comment by MBlesken** [comment]
> Please move any example code to the Reference FMUs repo and include it from there.

@t-sommer The pseudo code example is neither complete nor compilable. It is intended to focus on the crucial peculiarities of the SCS. It is my understanding that code in the Reference FMUs repo has to be compilable. Is that right? If so, we would rather not move the pseudo code there. Please note that there exists a compilable example for SCS in the Reference FMUs repo already.

**Comment by andreas-junghanns** [comment]
@MBlesken , @IZacharias : this PR is still in draft status. Is this on purpose, or can we review and merge if ok?

**Comment by t-sommer** [comment]
> Please note that there exists a compilable example for SCS in the Reference FMUs repo already.

Can't we include this example or parts thereof?

**Comment by MBlesken** [comment]
I'm cancelling this PR and created PR #1116 instead.

**Pull request closed without merging**
